### ISSUE TITLE
(qlearn) maxQuality function changes order of actions

### ISSUE THREAD

**Issue by miran248** [GrosSacASac/JavaScript-Set-Up#74]
https://github.com/GrosSacASac/JavaScript-Set-Up/blob/master/js/ai/qlearn/source/qlearn.js#L14

Possible fix:
```
const maxQuality = (qualityForState) => {
    return [ ...qualityForState ].sort(([qualityA], [qualityB]) => {
        return qualityB - qualityA;
    })[0][0];
};
```

**Comment by GrosSacASac** [comment]
Thank you I will have a look

**Comment by GrosSacASac** [comment]
It looks like I used a sort + select the first to get the maximum value  ...

**Comment by GrosSacASac** [comment]
I will replace the internal array with a Map, it will simplify the code as well
