### ISSUE TITLE
(socketiyo) use eslint

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/JavaScript-Set-Up#84]
Use eslint with [JavaScript Red Style Guide](https://github.com/GrosSacASac/JavaScript-Set-Up/tree/master/js/red-javascript-style-guide)

**Comment by poojakp94** [comment]
@GrosSacASac I would like to work on this

**Comment by GrosSacASac** [comment]
Go ahead :)

**Comment by poojakp94** [comment]
@GrosSacASac There is no `package.json` in this project, so how do I add the Red Style config

**Comment by GrosSacASac** [comment]
The package.json is here https://github.com/GrosSacASac/JavaScript-Set-Up/tree/master/js/network/socketiyo

**Comment by GrosSacASac** [comment]
this issue is for the socketiyo project

**Comment by poojakp94** [comment]
Thanks.
